name: tea_tasting
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  flutter_inappwebview: ^6.0.0
  bot_toast: ^4.1.3
  flutter_screenutil: ^5.9.0
  dio: ^5.4.3+1
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.3
  faker: ^2.1.0
  image_picker: ^1.0.4
  flutter_timezone: ^1.0.8

  flutter_localizations:
    sdk: flutter
    
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/bo.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/bo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter: 
  uses-material-design: true
  assets:
    - assets/tea.json
    - assets/images/
